// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlfoLF8AM8l62jhvWqXFO_5fGigeQ2ZDY',
    appId: '1:1073154432086:web:b02f6e79c3b77ff3396ff7',
    messagingSenderId: '1073154432086',
    projectId: 'lifeplanner-582ee',
    authDomain: 'lifeplanner-582ee.firebaseapp.com',
    storageBucket: 'lifeplanner-582ee.firebasestorage.app',
    measurementId: 'G-K8QZCYW2DL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbNADFrp7GRf9jlFBj5Gan_Nd-bBZYlyA',
    appId: '1:1073154432086:android:e24c98bbb7f24d52396ff7',
    messagingSenderId: '1073154432086',
    projectId: 'lifeplanner-582ee',
    storageBucket: 'lifeplanner-582ee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKD1UFdKx8SISdEhZlw8ieIliqd8hb6cM',
    appId: '1:1073154432086:ios:51958297a9afde85396ff7',
    messagingSenderId: '1073154432086',
    projectId: 'lifeplanner-582ee',
    storageBucket: 'lifeplanner-582ee.firebasestorage.app',
    iosBundleId: 'com.example.lifePlanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKD1UFdKx8SISdEhZlw8ieIliqd8hb6cM',
    appId: '1:1073154432086:ios:51958297a9afde85396ff7',
    messagingSenderId: '1073154432086',
    projectId: 'lifeplanner-582ee',
    storageBucket: 'lifeplanner-582ee.firebasestorage.app',
    iosBundleId: 'com.example.lifePlanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlfoLF8AM8l62jhvWqXFO_5fGigeQ2ZDY',
    appId: '1:1073154432086:web:8ad9205986bd7315396ff7',
    messagingSenderId: '1073154432086',
    projectId: 'lifeplanner-582ee',
    authDomain: 'lifeplanner-582ee.firebaseapp.com',
    storageBucket: 'lifeplanner-582ee.firebasestorage.app',
    measurementId: 'G-Q0PGBVJT8G',
  );

}